project_id = "tlcdidkkxigofdhxnzzo"

[functions.sync-timers-and-protection]
verify_jwt = false

[functions.auction-webhook]
verify_jwt = false

[functions.mercado-pago-payment]
verify_jwt = false

[functions.mercado-pago-webhook]
verify_jwt = false

[functions.check-availability]
verify_jwt = false

[functions.send-email]
verify_jwt = false

[functions.admin-update-user-password]
verify_jwt = false

[functions.partner-weekly-payouts]
verify_jwt = false

[functions.partner-payment]
verify_jwt = false

[functions.partner-payment-webhook]
verify_jwt = false

[functions.partner-upgrade-payment]
verify_jwt = false

[functions.admin-delete-user]
verify_jwt = false

[functions.auto-replenish-auctions]
verify_jwt = false

[functions.sponsor-activate-partner]
verify_jwt = false
