project_id = "tlcdidkkxigofdhxnzzo"

[functions.sync-timers-and-protection]
verify_jwt = false

[functions.auction-webhook]
verify_jwt = false

[functions.mercado-pago-payment]
verify_jwt = false

[functions.mercado-pago-webhook]
verify_jwt = false

[functions.check-availability]
verify_jwt = false

[functions.send-email]
verify_jwt = false

[functions.admin-update-user-password]
verify_jwt = false

[functions.partner-weekly-payouts]
verify_jwt = false
